from Objects.DangerZone import DangerZone
from Objects.Red1 import Red1
from Objects.Red2 import Red2
from Objects.Red3 import Red3
from Objects.Red4 import Red4
from Objects.Red5 import Red5
from Objects.Blue1 import Blue1
from Objects.Blue2 import Blue2
from Objects.Blue3 import Blue3
from Objects.Blue4 import Blue4
from Objects.Blue5 import Blue5
